# Regression Models in R (tips)

In [1]:
import pandas as pd
import sweetviz as sv

In [22]:
df = pd.read_csv("train.csv")
df.head()

,id,season,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,985
1,2,1,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,801
2,3,1,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,1349
3,4,1,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,1562
4,5,1,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,1600

Data Set Information:

Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues.

Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.


Attribute Information:

Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv

- instant: record index
- season : season (1:winter, 2:spring, 3:summer, 4:fall)
- mnth : month ( 1 to 12)
- hr : hour (0 to 23)
- holiday : weather day is holiday or not (extracted from [Web Link])
- weekday : day of the week
- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
+ weathersit :
- 1: Clear, Few clouds, Partly cloudy, Partly cloudy
- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)
- atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)
- hum: Normalized humidity. The values are divided to 100 (max)
- windspeed: Normalized wind speed. The values are divided to 67 (max)
- casual: count of casual users
- registered: count of registered users
- cnt: count of total rental bikes including both casual and registered

# EDA

In [23]:
df1 = df.season.astype(str).str.get_dummies()
df1.columns = ['season_' + col for col in df1.columns]
df = pd.concat([df, df1], axis=1)
#del df['season']

df1 = df.mnth.astype(str).str.get_dummies()
df1.columns = ['mnth' + col for col in df1.columns]
df = pd.concat([df, df1], axis=1)
#del df['mnth']

df1 = df.weekday.astype(str).str.get_dummies()
df1.columns = ['weekday' + col for col in df1.columns]
df = pd.concat([df, df1], axis=1)
#del df['weekday']

df1 = df.weathersit.astype(str).str.get_dummies()
df1.columns = ['weathersit' + col for col in df1.columns]
df = pd.concat([df, df1], axis=1)
#del df['weathersit']

df

,id,season,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,...,weekday0,weekday1,weekday2,weekday3,weekday4,weekday5,weekday6,weathersit1,weathersit2,weathersit3
0,1,1,1,0,6,0,2,0.344167,0.363625,0.805833,...,0,0,0,0,0,0,1,0,1,0
1,2,1,1,0,0,0,2,0.363478,0.353739,0.696087,...,1,0,0,0,0,0,0,0,1,0
2,3,1,1,0,1,1,1,0.196364,0.189405,0.437273,...,0,1,0,0,0,0,0,1,0,0
3,4,1,1,0,2,1,1,0.200000,0.212122,0.590435,...,0,0,1,0,0,0,0,1,0,0
4,5,1,1,0,3,1,1,0.226957,0.229270,0.436957,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,361,1,12,0,2,1,2,0.325000,0.327633,0.762500,...,0,0,1,0,0,0,0,0,1,0
361,362,1,12,0,3,1,1,0.299130,0.279974,0.503913,...,0,0,0,1,0,0,0,1,0,0
362,363,1,12,0,4,1,1,0.248333,0.263892,0.574167,...,0,0,0,0,1,0,0,1,0,0
363,364,1,12,0,5,1,1,0.311667,0.318812,0.636667,...,0,0,0,0,0,1,0,1,0,0
364,365,1,12,0,6,0,1,0.410000,0.414121,0.615833,...,0,0,0,0,0,0,1,1,0,0

In [25]:
import sweetviz as sv

#analyzing the dataset
advert_report = sv.analyze(df)
#display the report
advert_report.show_html('bikes.html')

:FEATURES DONE:                    |█████████████████████| [100%]   00:04  -> (00:00 left)
:PAIRWISE DONE:                    |█████████████████████| [100%]   00:00  -> (00:00 left)

Creating Associations graph... DONE!
Report bikes.html was generated! NOTEBOOK/COLAB USERS: no browser will pop up, the report is saved in your notebook/colab files.

In [7]:
df$holiday <- as.factor(df$holiday)
df$workingday <- as.factor(df$workingday)

df["season_1"] = as.factor(df$season_1)
df["season_2"] = as.factor(df$season_2)
df["season_3"] = as.factor(df$season_3)
df["season_4"] = as.factor(df$season_4)

df["mnth_1"] = as.factor(df$mnth_1)
df["mnth_2"] = as.factor(df$mnth_2)
df["mnth_3"] = as.factor(df$mnth_3)
df["mnth_4"] = as.factor(df$mnth_4)
df["mnth_5"] = as.factor(df$mnth_5)
df["mnth_6"] = as.factor(df$mnth_6)
df["mnth_7"] = as.factor(df$mnth_7)
df["mnth_8"] = as.factor(df$mnth_8)
df["mnth_9"] = as.factor(df$mnth_9)
df["mnth_10"] = as.factor(df$mnth_10)
df["mnth_11"] = as.factor(df$mnth_11)
df["mnth_12"] = as.factor(df$mnth_12)

df["weekday_0"] = as.factor(df$weekday_0)
df["weekday_1"] = as.factor(df$weekday_1)
df["weekday_2"] = as.factor(df$weekday_2)
df["weekday_3"] = as.factor(df$weekday_3)
df["weekday_4"] = as.factor(df$weekday_4)
df["weekday_5"] = as.factor(df$weekday_5)
df["weekday_6"] = as.factor(df$weekday_6)

df["weathersit_1"] = as.factor(df$weathersit_1)
df["weathersit_2"] = as.factor(df$weathersit_2)
df["weathersit_3"] = as.factor(df$weathersit_3)

SyntaxError: invalid syntax (<ipython-input-7-bb5a7acd0bdb>, line 1)